### ISSUE TITLE
More pre-commit

### ISSUE THREAD

**Issue by felixhekhorn** [N3PDF/pineko#34]
Taking some inspiration from poetry https://github.com/python-poetry/poetry/blob/master/.pre-commit-config.yaml I suggest to update our pre-commit config
1. by opting into
    ```
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-ast
      - id: check-docstring-first
    ```
2. adding
   ```
    - repo: https://github.com/pre-commit/pre-commit
      rev: v2.20.0
      hooks:
        - id: validate_manifest
   ```
3. opting into https://pre-commit.ci/ (with `autofix_prs: false`) to enforce people running pre-commit (right @andreab1997 ? :upside_down_face: )

what do you think? @AleCandido @andreab1997 @niclaurenti @giacomomagni
